# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alsi/Downloads/SkyFall_Legends_99999

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alsi/Downloads/SkyFall_Legends_99999/build

# Include any dependencies generated for this target.
include CMakeFiles/SkyfallLegends.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/SkyfallLegends.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/SkyfallLegends.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/SkyfallLegends.dir/flags.make

CMakeFiles/SkyfallLegends.dir/codegen:
.PHONY : CMakeFiles/SkyfallLegends.dir/codegen

CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/engine/CoreEngine.cpp
CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/engine/CoreEngine.cpp

CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/engine/CoreEngine.cpp > CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.i

CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/engine/CoreEngine.cpp -o CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.s

CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Boss.cpp
CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Boss.cpp

CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Boss.cpp > CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.i

CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Boss.cpp -o CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.s

CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Bullet.cpp
CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Bullet.cpp

CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Bullet.cpp > CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.i

CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Bullet.cpp -o CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.s

CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Enemy.cpp
CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Enemy.cpp

CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Enemy.cpp > CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.i

CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Enemy.cpp -o CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.s

CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Explosion.cpp
CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Explosion.cpp

CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Explosion.cpp > CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.i

CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Explosion.cpp -o CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.s

CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Player.cpp
CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Player.cpp

CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Player.cpp > CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.i

CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/Player.cpp -o CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.s

CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/PowerUp.cpp
CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/PowerUp.cpp

CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/PowerUp.cpp > CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.i

CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/entities/PowerUp.cpp -o CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.s

CMakeFiles/SkyfallLegends.dir/src/main.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/main.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/main.cpp
CMakeFiles/SkyfallLegends.dir/src/main.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/main.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/main.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/main.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/main.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/main.cpp

CMakeFiles/SkyfallLegends.dir/src/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/main.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/main.cpp > CMakeFiles/SkyfallLegends.dir/src/main.cpp.i

CMakeFiles/SkyfallLegends.dir/src/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/main.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/main.cpp -o CMakeFiles/SkyfallLegends.dir/src/main.cpp.s

CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/AISystem.cpp
CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/AISystem.cpp

CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/AISystem.cpp > CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.i

CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/AISystem.cpp -o CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.s

CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/WaveManager.cpp
CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/WaveManager.cpp

CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/WaveManager.cpp > CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.i

CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/ai/WaveManager.cpp -o CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.s

CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/input/InputManager.cpp
CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/input/InputManager.cpp

CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/input/InputManager.cpp > CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.i

CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/input/InputManager.cpp -o CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.s

CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/physics/PhysicsSystem.cpp
CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/physics/PhysicsSystem.cpp

CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/physics/PhysicsSystem.cpp > CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.i

CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/physics/PhysicsSystem.cpp -o CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.s

CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/rendering/Renderer.cpp
CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/rendering/Renderer.cpp

CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/rendering/Renderer.cpp > CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.i

CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/modules/rendering/Renderer.cpp -o CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.s

CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/HUD.cpp
CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/HUD.cpp

CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/HUD.cpp > CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.i

CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/HUD.cpp -o CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.s

CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o: CMakeFiles/SkyfallLegends.dir/flags.make
CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o: /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/Menu.cpp
CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o: CMakeFiles/SkyfallLegends.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building CXX object CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o -MF CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o.d -o CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o -c /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/Menu.cpp

CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/Menu.cpp > CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.i

CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/alsi/Downloads/SkyFall_Legends_99999/src/ui/Menu.cpp -o CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.s

# Object files for target SkyfallLegends
SkyfallLegends_OBJECTS = \
"CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/main.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o" \
"CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o"

# External object files for target SkyfallLegends
SkyfallLegends_EXTERNAL_OBJECTS =

SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/engine/CoreEngine.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/entities/Boss.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/entities/Bullet.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/entities/Enemy.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/entities/Explosion.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/entities/Player.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/entities/PowerUp.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/main.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/modules/ai/AISystem.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/modules/ai/WaveManager.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/modules/input/InputManager.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/modules/physics/PhysicsSystem.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/modules/rendering/Renderer.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/ui/HUD.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/src/ui/Menu.cpp.o
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/build.make
SkyfallLegends: /opt/homebrew/lib/libsfml-graphics.2.6.2.dylib
SkyfallLegends: /opt/homebrew/lib/libsfml-audio.2.6.2.dylib
SkyfallLegends: /opt/homebrew/lib/libsfml-window.2.6.2.dylib
SkyfallLegends: /opt/homebrew/lib/libsfml-system.2.6.2.dylib
SkyfallLegends: CMakeFiles/SkyfallLegends.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Linking CXX executable SkyfallLegends"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/SkyfallLegends.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/SkyfallLegends.dir/build: SkyfallLegends
.PHONY : CMakeFiles/SkyfallLegends.dir/build

CMakeFiles/SkyfallLegends.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/SkyfallLegends.dir/cmake_clean.cmake
.PHONY : CMakeFiles/SkyfallLegends.dir/clean

CMakeFiles/SkyfallLegends.dir/depend:
	cd /Users/alsi/Downloads/SkyFall_Legends_99999/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/alsi/Downloads/SkyFall_Legends_99999 /Users/alsi/Downloads/SkyFall_Legends_99999 /Users/alsi/Downloads/SkyFall_Legends_99999/build /Users/alsi/Downloads/SkyFall_Legends_99999/build /Users/alsi/Downloads/SkyFall_Legends_99999/build/CMakeFiles/SkyfallLegends.dir/DependInfo.cmake "--color=$(COLOR)" SkyfallLegends
.PHONY : CMakeFiles/SkyfallLegends.dir/depend

