# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I/Users/alsi/Downloads/SkyFall_Legends_99999/src -isystem /opt/homebrew/include

CXX_FLAGSarm64 = -std=gnu++17 -arch arm64

CXX_FLAGS = -std=gnu++17 -arch arm64

